routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

#Authentification
//Clear Cache facade value:
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    return '<h1>Cache facade value cleared</h1>';
});

//Reoptimized class loader:
Route::get('/optimize', function() {
    $exitCode = Artisan::call('optimize');
    return '<h1>Reoptimized class loader</h1>';
});

//Route cache:
Route::get('/route-cache', function() {
    $exitCode = Artisan::call('route:cache');
    return '<h1>Routes cached</h1>';
});

//Clear Route cache:
Route::get('/route-clear', function() {
    $exitCode = Artisan::call('route:clear');
    return '<h1>Route cache cleared</h1>';
});

//Clear View cache:
Route::get('/view-clear', function() {
    $exitCode = Artisan::call('view:clear');
    return '<h1>View cache cleared</h1>';
});

//Clear Config cache:
Route::get('/config-cache', function() {
    $exitCode = Artisan::call('config:cache');
    return '<h1>Clear Config cleared</h1>';
});
Route::get('/view-cache', function() {
     $exitCode = Artisan::call('view:cache');
    return '<h1>Clear View cache</h1>';
});

Auth::routes();
Route::get('test/{slug}',function($slug){
  if($slug=="db"){
    try {
      $db=DB::connection()->getPdo();
      echo "Connecion Réussie";
    } catch (\Exception $e) {
      die("Could not connect to the database.  Please check your configuration. error:" . $e->getMessage() );
    }
  }
  return "<hr>TEST :".$slug;
});
Route::name('language')->get('lang/{lang}', 'LangueController@ChangerLang');
Route::get('login/google', 'Auth\LoginController@redirectToProvider');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback');//user_profil

Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback')->name('user_profil');//user_profil

Route::get('/', 'Apps\PageController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/@{id}', 'HomeController@index')->name('user_profil');
Route::get('login/{provider}', 'SocialController@redirect');
Route::get('login/{provider}/callback','SocialController@Callback');

#Apps

Route::get('/dashboard', 'Apps\AppsController@index')->name('dashboard');
Route::get('/app/{fichier}', 'Apps\AppsController@DetailsBien')->name('DetailsBien');
#Bien de chaque utilisateur
#API
Route::get('/api/v1/getUser', 'Apps\BienController@getUser')->name('apiv1GetUser');
Route::get('/help', 'Apps\PageController@help')->name('help_apps');


Route::get('/new', 'Apps\BienController@create')->name('create_bien');
Route::post('/new', 'Apps\BienController@store')->name('store_bien');
Route::get('/bien/edit/{id}', 'Apps\BienController@edit')->name('edit_bien');
Route::get('/bien/{id}', 'Apps\BienController@show')->name('show_bien');
Route::get('/bien/trash/{id}', 'Apps\BienController@trash')->name('trash_bien');
Route::delete('/bien/delete/{id}', 'Apps\BienController@delete')->name('delete_bien');
Route::patch('/bien/edit/{id}', 'Apps\BienController@update')->name('update_bien');
Route::get('/bien/favori/{id}', 'Apps\BienController@add_bien_favori')->name('add_bien_favori');//delete_bien_favori
Route::get('/bien/unfavori/{id}', 'Apps\BienController@delete_bien_favori')->name('delete_bien_favori');

Route::get("/favoris", 'Apps\AppsController@bien_favoris')->name('bien_favoris');
Route::get("/classement", 'Apps\AppsController@classement')->name('classement');
Route::get("/export/favoris", 'Apps\AppsController@export_favoris')->name('export_favoris');
Route::get("/export/bien/all", 'Apps\AppsController@export_all')->name('export_all_biens');
Route::get('/export/bien/{id}', 'Apps\AppsController@export_bien')->name('export_bien');//
Route::get('/export/bien/mode/{slug}', 'Apps\AppsController@export_mode')->name('export_mode');//
Route::get('/export/bien/categorie/{id}', 'Apps\AppsController@export_categorie')->name('export_categorie');//

Route::get('/notifications', 'Apps\ProfilController@notification')->name('notification');
Route::get('/profil/{id}', 'Apps\ProfilController@profil')->name('profil');
Route::get('/account/edition', 'Apps\ProfilController@edit_profil')->name('edit_profil');
Route::get('/account/settings', 'Apps\ProfilController@profil_settings')->name('profil_settings');
Route::get('/help/center', 'Apps\ProfilController@help_center')->name('help_center');
Route::get('/language/settings', 'Apps\ProfilController@lang_settings')->name('lang_settings');
Route::get('/account/security', 'Apps\ProfilController@account_security')->name('account_security');
Route::get('/account/business', 'Apps\ProfilController@account_business')->name('account_business');


Route::get('/bien/classement/mode/{slug}', 'Apps\AppsController@classement_mode')->name('classement_mode');//classement_mode
Route::get('/bien/classement/categorie/{id}', 'Apps\AppsController@classement_categorie')->name('classement_categorie');//classement_mode

Route::get('/about', 'Apps\PageController@about')->name('about');
Route::get('/terms', 'Apps\PageController@condition')->name('condition');
Route::get('/privacy', 'Apps\PageController@reglement')->name('reglement');
Route::get('/cookies', 'Apps\PageController@cookies')->name('cookies');
Route::get('/soumission', 'Apps\PageController@soumission')->name('soumission');

#Route::update('/new/{id}', 'Apps\BienController@update')->name('update_bien');
##########################################################################
#    VISUALISATION D'UN BIEN
##########################################################################
Route::get('/bien/{id}/activity', 'Apps\BienController@show_activite')->name('show_activite_bien');
Route::get('/bien/{id}/movement', 'Apps\BienController@show_mouvement')->name('show_mouvement_bien');
Route::get('/bien/{id}/security', 'Apps\BienController@show_securite')->name('show_securite_bien');
Route::get('/bien/{id}/accessory', 'Apps\BienController@show_accessoire')->name('show_accessoire_bien');
Route::get('/bien/{id}/statistique', 'Apps\BienController@show_statistique')->name('show_statistique_bien');



Route::get('/test',function(){
  return view('web.test2');
});
Route::resource('admin/posts', 'Admin\\PostsController');
Route::resource('admin/type-transfert', 'Admin\\TypeTransfertController');
Route::resource('admin/posts', 'Admin\\PostsController');
Route::resource('admin/modeacquisition', 'Admin\\ModeacquisitionController');
Route::resource('admin/typebien', 'Admin\\TypebienController');
Route::resource('admin/marque', 'Admin\\MarqueController');
Route::resource('admin/marque', 'Admin\\MarqueController');
Route::resource('admin/modele', 'Admin\\ModeleController');
Route::resource('admin/media', 'Admin\\MediaController');
Route::resource('favori', 'FavoriController');
Route::resource('admin/devise', 'Admin\\DeviseController');

Route::get('nom', 'Apps\PageController@nom');

Route::get('rcours/{slug}', 'Apps\PageController@rcours');
Route::get('icours/{slug}', 'Apps\PageController@icours');

resources/views/admin/___.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        Your application's dashboard.
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sidebar.blade.php
<style>
   
</style>
<div class="col-md-2 col-sm-3 pr0 mtop10">
    @include("apps.includes.nav.mini-profil")
    <div class="slime_menu">
        

        <div class="">
            <ul class="nav slime_nav"  role="tablist">
                <li role="presentation">
                    <a href="{{ url('/admin') }}">
                    <i class="icon icon-home"></i>
                      {{__('Tableau de board')}}
                    </a>
                </li>
                <li role="presentation">
                    <a href="{{ route('modeacquisition.index') }}">
                    <i class="icon icon-peoples"></i>
                    {{__("Mode d'acquisition")}}
                    </a>
                </li>
                <li role="presentation">
                    <a href="{{ route('typebien.index') }}">
                    <i class="icon icon-peoples"></i>
                    {{__("Type de bien")}}
                    </a>
                </li>
                <li role="presentation">
                    <a href="{{ route('devise.index') }}">
                        <i class="icon icon-peoples"></i>
                        {{__("Devise ")}}
                    </a>
                </li>
                <li role="presentation">
                    <a href="{{ url('/users') }}">
                    <i class="icon icon-people"></i>
                    {{__('Les utilisateurs')}}
                    </a>
                </li>
                <li role="presentation">
                    <a href="{{ url('/biens') }}">
                    <i class="icon icon-bag"></i>
                    {{__('Biens')}}
                    </a>
                </li>
                <li role="presentation">
                    <a href="{{ url('/typebien') }}">
                    <i class="icon icon-handbag"></i>
                    {{__('Type de bien')}}
                    </a>
                </li>
                <li role="presentation">
                    <a href="{{ url('/transfert') }}">
                    <i class="icon icon-shuffle"></i>
                    {{__('Transferts')}}
                    </a>
                </li>
                <li role="presentation">
                    <a href="{{ url('/blog/article') }}">
                    <i class="icon icon-bulb"></i>
                    {{__('Le Blog')}}
                    </a>
                </li>
                <li role="presentation">
                    <a href="{{ url('/Blog/categorie') }}">
                    <i class="icon icon-grid"></i>
                    {{__("Types d'article")}}
                    </a>
                </li>
                <li role="presentation">
                    <a href="{{ url('/admin') }}">
                    <i class="icon icon-bubbles"></i>
                    {{__('Forum')}}
                    </a>
                </li>
                <li role="presentation">
                    <a href="{{ url('/traductions') }}">
                    <i class="icon icon-flag"></i>
                    {{__('Traductions')}}
                    </a>
                </li>
                <li role="presentation">
                    <a href="{{ url('/admin') }}">
                    <i class="icon icon-equalizer"></i>
                    {{__('Paramètres')}}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>